### ISSUE TITLE
PO files are corrupted

### ISSUE THREAD

**Issue by jonmcp** [bigbitecreative/benenson#12]
## Expected Behavior
Updating PO catalogues from source code should run successfully.

## Actual Behavior
![](http://bigbite.im/JqJ0ay+)

## Steps to Reproduce the Problem

  1. Open a PO file
  2. Update the catalogue

## Specifications

  - Browser: N/A
  - Platform: Mac OS X (High Sierra), Poedit v2.2 (5561)

**Comment by ampersarnie** [comment]
Looks like there's a duplicate for the `msgid` `Benenson` when checking for errors in the translation files.

```
#: header.php:69
#: includes/blocks/block-category.php:15
```

I'll take this one to sort.
