### ISSUE TITLE
[QUESTION] Change Logo

### ISSUE THREAD

**Issue by nickw108** [bigbitecreative/benenson#137]
Thanks for sharing this theme and child theme. I saw _logo and _logo_url in the theme options wiki, but don't understand how I would change the logo in the child theme. It looks like it's not available in the customizer, so I guess it has to be added somewhere in the child theme code?

**Comment by jonmcp** [comment]
Hi @nickw108; sorry for the slow reply.

Whilst we do intend to switch to using the Customizer in v1.1.0, we currently use a Theme Settings page under Appearance in the admin, which allows you to update all of the settings listed in the Wiki, including the logo.

I hope that helps, and thanks for checking out the theme 😃
