### ISSUE TITLE
[BUG] GA is always enqueued, even without a valid tag

### ISSUE THREAD

**Issue by jonmcp** [bigbitecreative/benenson#51]
**Describe the bug**
Google Analytics support has a default option fallback of `test` [here](https://github.com/bigbitecreative/benenson/blob/master/includes/analytics-output.php#L47).  
This means that the GTM script is _always_ output, even if the user has no desire to use GA. Users would have to unhook the call to prevent the script from outputting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install & activate the theme.

**Expected behaviour**
When no GA code is added to the theme's options, no GTM script should be output.

**Screenshots**
![](http://bigbite.im/EwRcwn+)  
![](http://bigbite.im/Dm4mfi+)

**Platform (please complete the following information):**
Platform-independent. Affects all versions of Benenson.

**Comment by ampersarnie** [comment]
Annoying that ended up in there.
